name: example
description: Describes how to use strava_flutter package
  to access Strava v3 API

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+5

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  html: ^0.14.0+3  # to remove the # at the end of the redirect url

  # strava_flutter: ^1.0.6+17
  # To test locally
  strava_flutter: 
    path: ../   

  # path_provider: ^1.2.0   # To access to the gpx file used to upload
  path_provider: ^1.2.0   # To access to the gpx file used to upload

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  # NOT working for the moment
  flutter_driver:
    sdk: flutter
  test: any

  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Ride in gpx format to test uploadActivity
  assets:
    - assets/Bormes.gpx

