name: strava_client
description: A Flutter Client for Strava V3 Api Based on the old strava_flutter api.
version: 3.0.0
homepage: https://github.com/dreampowder/strava_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_web_auth_2: ^4.0.1
  get_it: ^8.0.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: 1.5.3 # To launch some tests in /test

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
