name: strava_client
description:  A Flutter Client for Strava V3 Api Based on the old strava_flutter api.
version: 2.1.0
homepage: https://github.com/dreampowder/strava_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_web_auth: ^0.5.0
  get_it: ^7.2.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: 1.5.3 # To launch some tests in /test

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
