name: strava_flutter
description:  Fluytter/Dart code to access Strava v3 API including new authentication process (with expired date and refresh token)
version: 1.2.2+62
homepage: https://github.com/BirdyF/strava_flutter

environment:
  #sdk: ">=2.0.0-dev.68.0 <3.0.0"
  sdk: ">=2.1.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+1 
  url_launcher: ^5.4.5  
  shared_preferences: ^0.5.0
 
  uni_links: ^0.4.0

  #intl: ^0.15.8
  intl: ^0.16.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: 1.5.3 # To launch some tests in /test

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  


