name: strava_client
description:  A Flutter Client for Strava V3 Api Based on the old strava_flutter api.
version: 2.0.2
homepage: https://github.com/dreampowder/strava_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.1.8
  shared_preferences: ^2.0.17
  uni_links: ^0.5.1
  intl: ^0.17.0
  dio: ^4.0.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # test: 1.5.3 # To launch some tests in /test

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
